Create cdo-automation example for devnet-lab
CiscoDevNet/cdo-automation pull request #1
Opened 2023-09-20 17:16 UTC by siddhuwarrier

2023-09-21 09:18 UTC, weilueluo requested changes
Looks good overall, just some small comments

2023-09-21 09:18 UTC, weilueluo commented on modules/aws_vpc/private_subnet.tf
> +    Name : "cdo-provider-example-private-route-table"
nit: pass in `cdo-provider-example` as a `tag-prefix` variable

2023-09-21 09:18 UTC, weilueluo commented on modules/asav/ec2.tf
> +  }
I wonder what is the reason behind this?

2023-09-21 09:18 UTC, weilueluo commented on modules/bastion/ec2.tf
>      instanceType : "bastion",
small typo: should be `InstanceType`

2023-09-21 09:18 UTC, weilueluo commented on modules/bastion/ec2.tf
> -  iam_instance_profile        = aws_iam_instance_profile.lab-iam-profile.id
Is this intended? Can user still ssh into bastion normally?

2023-09-21 09:18 UTC, weilueluo commented on modules/cdo/asa/main.tf
> +  socket_address = "${module.terraform-managed-asav-01.mgmt_interface_ip}:443"
nit: `port` as variable with default `443`

2023-09-21 09:18 UTC, weilueluo commented on modules/ftdv/ec2.tf
> +  }
do we need `ignore_changes` here when the `ami` is a variable? Seems like it is potentially going to cause confusing behaviour to the user of this module, where they change the ami but the instance did not get recreated

2023-09-22 16:03 UTC, siddhuwarrier commented on modules/cdo/asa/main.tf
> +  socket_address = "${module.terraform-managed-asav-01.mgmt_interface_ip}:443"
Fixed

2023-09-22 16:25 UTC, siddhuwarrier commented on modules/asav/ec2.tf
> +  }
This is so that we do not end up redeploying the EC2 instance every time a new AMI comes out.

2023-09-22 16:26 UTC, siddhuwarrier commented on modules/bastion/ec2.tf
> -  iam_instance_profile        = aws_iam_instance_profile.lab-iam-profile.id
IAM instance profiles are for SSM, not SSH. I don't want to add support for it in the lab because it will confuse people.

2023-09-22 16:26 UTC, siddhuwarrier commented on modules/ftdv/ec2.tf
> +  }
Yes. This is so that we do not end up redeploying the EC2 instance every time a new AMI comes out. There are no users for this module beyond people using this as an example.

2023-09-22 16:27 UTC, siddhuwarrier commented on modules/bastion/ec2.tf
>      instanceType : "bastion",
Fixed

2023-09-22 16:29 UTC, siddhuwarrier commented on modules/aws_vpc/private_subnet.tf
> +    Name : "cdo-provider-example-private-route-table"
Done, thanks.

2023-09-22 16:33 UTC, weilueluo approved these changes
LGTM!

2023-09-22 16:34 UTC, merged